Pull Request
Marist-CMPT331-TOPL/adder pull request #17
Opened 2022-11-22 04:27 UTC by seanygberg

This is my implementation for some of the operators. I still have to figure out how to put these into the interpreter, but this is my current syntax.

2022-11-22 17:53 UTC, Trent325 reviewed
The addition of the operators and their parser looks correct. I am not entirely sure but I believe it is.

2022-11-22 21:44 UTC, rvarca22 commented
Would you not also have to add the operators '//' and '%' into the operator precedence table in Parser? I believe mod takes precedence over + and -

2022-11-22 22:08 UTC, Gjidodaj02 commented
From what I see it looks like you implemented them well. Not too sure though since I settled with implementing easier operators lol, so its harder for me to compare.

2022-11-29 17:37 UTC, Tientuine requested changes
Almost there!

2022-11-29 17:37 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["%", "//", "/"]
FYI, someone else (Tevie) is also working on remainder/modulus because you never "claimed" it in the Issues (i.e., wrote your name next to it).

Otherwise, this looks fine.

2022-11-29 17:37 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ],
To make sure that these operators all have the same precedence, which they should, you must put them together in the same "row" of the `table`. In other words, they should all be in the same sub-list, rather than in separate lists.

2022-11-29 17:37 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | Divide
Good.

2022-12-01 14:07 UTC, Tientuine requested changes
Just add the `*` operator to the list of reserved operator names, and then you're all set for merge!

2022-12-01 14:07 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    Infix (reservedOp "%" >> return (BinaryExpr Mod)) AssocLeft],
Better!

2022-12-01 14:07 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  deriving (Eq, Ord, Show)
Not really needed, but fine.

2022-12-01 14:07 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["%", "//", "/"]
Actually, we also need the multiplication operator `*` in this list.

2022-12-01 16:59 UTC, Tientuine approved these changes
Yay!

2022-12-01 17:01 UTC, merged