Assignment 3
Marist-CMPT331-TOPL/adder pull request #18
Opened 2022-11-22 17:52 UTC by Trent325

I attempted to do assignment 3, it is probably wrong, so feedback is appreciated. Thank you

2022-11-22 18:23 UTC, seanygberg commented
I think you have the right idea as to how everything should be implemented. The one thing I will say is when you define it in simple statement in the Parser, it think you just need (reserved "return" >> [expression] ) instead of (reserved "return" >> return [expression] ). I could be wrong, but I think that is how you could do it.

2022-11-22 21:51 UTC, rvarca22 commented
Looks good to me. You should probably name your expression in Syntax "ReturnExpr" just to keep the naming convention for expressions in the language. Not sure if you're allowed to have a space in the name of an expression anyway. 

I also agree with Sean's comment, the return statement in the Parser should read "reserved 'return' >> Expression" you don't need the second return

2022-11-28 17:27 UTC, Tientuine requested changes

2022-12-01 17:34 UTC, Tientuine approved these changes
A couple of formatting issues, but I'll just fix these when doing the merge. In the meantime, try to figure out the VSCode + Haskell extensions problem so all future work can be formatting properly.

2022-12-01 17:34 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Fine. Formatting is off, but at this point I'll just fix it when resolving the merge conflicts.

2022-12-01 17:34 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +
Don't really need these extra empty lines, but okay.

2022-12-01 17:34 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Good for now.

2022-12-01 17:34 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  =  ReturnStmt Expression  -- I did this to return just an expression of any kind, so the user could use return for many purposes -- TODO Remove this after adding legit data constructors
Looks good for now.

2022-12-01 17:36 UTC, merged