Assignment 3 - Marsh
Marist-CMPT331-TOPL/adder pull request #19
Opened 2022-11-22 18:10 UTC by IanMarsh1

Still have issues with the Parser.hs file and trying to get the stack. Error below:

> src\Adder\Lang\Parser.hs:48:19: error:

    * Couldn't match type Statement with [Statement]
      Expected: ParsecT String () (IndentT Identity) [Statement]
        Actual: IParser Statement
    * In the second argument of (<$>), namely statement
      In the expression: Pgm <$> statement
      In an equation for `program': program = Pgm <$> statement
     |
48 | program = Pgm <$> statement
     |______________________^^^^^^^^^

2022-11-22 18:27 UTC, Tientuine commented
> Still have issues with the Parser.hs file and trying to get the stack. Error below:
> 
> > src\Adder\Lang\Parser.hs:48:19: error:
> 
> ```
> * Couldn't match type Statement with [Statement]
>   Expected: ParsecT String () (IndentT Identity) [Statement]
>     Actual: IParser Statement
> * In the second argument of (<$>), namely statement
>   In the expression: Pgm <$> statement
>   In an equation for `program': program = Pgm <$> statement
>  |
> ```
> 
> 48 | program = Pgm <$> statement |______________________^^^^^^^^^

It's useful to note here that `ParsecT String () (IndentT Identity)` means the same thing as `IParser` in this context. So, what it's telling you is that `Pgm <$> statement` gives you an `IParser Statement`, but what it needs is an `IParser [Statement]`. That's because the `statement` function is an `IParser Statement`.

This is where the `block` function that I mentioned earlier in the Zoom would be useful. The type of the block function is `block :: IParser a -> IParser [a]`. In other words, if you give is a function that parses an `a` value, then it creates a function that parses an sequence of `a`s on separate lines, as long as they're all indented the same amount (which is what we want).

2022-11-22 19:41 UTC, seanygberg commented
The pass statement looks to be implemented correctly. I don't know if you need to add "return PassStmt" when you define it in the parser. I could be wrong, but I don't think you need it.

2022-11-28 17:39 UTC, Tientuine requested changes
A few things need fixing (see below), but this is close and a good start.

2022-11-28 17:39 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["pass"],
Good!

2022-11-28 17:39 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +program = Pgm <$> statement
It's useful to note here that `ParsecT String () (IndentT Identity)` means the same thing as `IParser` in this context. So, what it's telling you is that `Pgm <$> statement` gives you an `IParser Statement`, but what it needs is an `IParser [Statement]`. That's because the `statement` function is an `IParser Statement`.

This is where the `block` function that I mentioned earlier in the Zoom would be useful. The type of the `block` function is `block :: IParser a -> IParser [a]`. In other words, if you give it a function that parses an `a` value, then it creates a function that parses an sequence of `a`s on separate lines, as long as they're all indented the same amount (which is what we want).

As an example, if we write `block identifier` that will have type `IParser [String]` and will parse an indented block of `identifier`s, each identifier on its own line and all lines indented the same amount. Of course, we don't want a block of identifiers... we want a block of `statement`s.

2022-11-28 17:39 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
This is very close... however, if we look at the Python language documentation, a `statement` can be either a `compoundStmt` or a `stmtList` (not just a single `simpleStmt`).

2022-12-01 17:40 UTC, Tientuine approved these changes
Looks ready for merge.

2022-12-01 17:40 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +program = Pgm <$> block statement
This change already in other branches, but okay. In the future, we should try to make sure that only one person makes a given change, so smoother merging.

2022-12-01 17:40 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Looks good.

2022-12-01 17:40 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    [ (reserved "pass" >> return PassStmt) -- pass_stmt ::= "pass"
Correct, but the parentheses are not needed.

2022-12-01 17:40 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Good. Technically not quite correct, since your code allows a statement list to be zero statements, which is not permitted in Python, but we can fix that later. Again, the outer parentheses are not necessary.

2022-12-01 17:40 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | StmtList [Statement]
Good.

2022-12-01 17:43 UTC, merged