Varca work
Marist-CMPT331-TOPL/adder pull request #20
Opened 2022-11-22 21:36 UTC by rvarca22

2022-11-22 22:03 UTC, Gjidodaj02 commented
From what I quickly scanned through, your implementation looks good.

2022-11-28 17:46 UTC, Tientuine requested changes
Good attempt here, very close - there are just a few fixes needed, see below for explanation and suggestions.

2022-11-28 17:46 UTC, Tientuine commented on src/Adder/Interp.hs
> +    st2 = resultOf conseq p st1
Nearly there... Haskell if-expressions need an else no matter what, you can't leave it out. So, for an if-statement that doesn't have an else block, what will be the resulting state if the test if false?

Also, an if-statement in Python will have a `suite` following the test, and a `suite` is a basically list of statements. So, the `conseq` symbol will actually refer to a list of statements rather than a single statement. Consequently (pun intended), you'll need to compute the result of each of these in sequence and then return the final state.

2022-11-28 17:46 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +program = Pgm <$> statement
Try to avoid making the same changes that another student is making (Ian also has this change in his branch), otherwise we will have merge conflicts.

Here are my comments to him about this one:

It's useful to note here that `ParsecT String () (IndentT Identity)` means the same thing as `IParser` in this context. So, what it's telling you is that `Pgm <$> statement` gives you an `IParser Statement`, but what it needs is an `IParser [Statement]`. That's because the `statement` function is an `IParser Statement`.

This is where the `block` function that I mentioned earlier in the Zoom would be useful. The type of the `block` function is `block :: IParser a -> IParser [a]`. In other words, if you give it a function that parses an `a` value, then it creates a function that parses an sequence of `a`s on separate lines, as long as they're all indented the same amount (which is what we want).

As an example, if we write `block identifier` that will have type `IParser [String]` and will parse an indented block of `identifier`s, each identifier on its own line and all lines indented the same amount. Of course, we don't want a block of identifiers... we want a block of `statement`s.

2022-11-28 17:46 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  = IfStmt  expression [statement]   -- If Statement contains Exprression and list of statements - at this time only one statement
Right idea, but you need capitalized `Expression` and `[Statement]` here because we need to refer to the types (not the functions in the Parser.hs file).

2022-11-29 16:30 UTC, rvarca22 commented on src/Adder/Lang/Syntax.hs
> +  = IfStmt  expression [statement]   -- If Statement contains Exprression and list of statements - at this time only one statement
Resolved

2022-12-01 16:16 UTC, rvarca22 commented on src/Adder/Lang/Parser.hs
> +program = Pgm <$> statement
resolved

2022-12-01 17:28 UTC, Tientuine approved these changes
Technically, there is a small mistake in the opLetters list, but I'll just fix that when fixing other merge conflicts so that we can move things along more quickly.

2022-12-01 17:28 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +      Tok.opLetter = oneOf "+-*/%@<>&|^~ := !.",
This is incorrect, there should be no whitespace among the operator letters.

2022-12-01 17:28 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +program = Pgm <$> block statement
This is correct, though Trent already has this in his branch. In the future, try to avoid having two people making the same changes.

2022-12-01 17:28 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +statement = compoundStmt -- for my
Okay.

2022-12-01 17:28 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +
Looks good.

2022-12-01 17:28 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  = IfStmt Expression [Statement] -- If Statement contains Exprression and list of statements - at this time only one statement
Good for now. Later we'll make this if-statement more flexible to handle other branches.

2022-12-01 17:30 UTC, merged