Missing stuff but unsure how to continue
Marist-CMPT331-TOPL/adder pull request #22
Opened 2022-11-23 01:05 UTC by Tones55

I am not sure where to go from here to finish assignment statements

2022-11-28 18:19 UTC, Tientuine requested changes
Good attempt, nearly there - just a few fixes needed as described below.

2022-11-28 18:19 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | AssignmentStmt Identifier Expression
Good.

2022-11-29 04:23 UTC, Tones55 commented
i have made the changes you suggested

2022-12-01 18:08 UTC, Tientuine approved these changes
I'll approve to keep things moving along, but in the future please avoid including non-changes (like removal of trailing newline in the file) in your commits.

2022-12-01 18:08 UTC, Tientuine commented on src/Adder/Interp.hs
> +-- interpreter (e.g., the applyProcedure helper function).
Please discard this change, as it's unnecessary.

2022-12-01 18:08 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Fine, but this will be overridden by commits from other branches when merged.

2022-12-01 18:08 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Looks good.

2022-12-01 18:11 UTC, merged