Break Statement
Marist-CMPT331-TOPL/adder pull request #23
Opened 2022-11-24 17:27 UTC by macc125

Implementation of break statement, with modifications to the following:

- Added reserved Op Names to Lexer
- Added: Negate, Greater, LessEq, GreaterEq, NotEqual operators

2022-11-28 18:39 UTC, Tientuine requested changes
There are some fixes needed, but it's good to see that you've started several of these new operators and the break statement. Of course, you won't be able to test the break statement until someone implements a loop.

You (or someone else) will also need to implement the behavior of these operations in the **Interp.hs** file.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["Not", "Negative", "IsNeg", "IsPos", "IsNull", "Negate", "Greater", "LessEq", "GreaterEq", "And", "Is", "Negate", "Break"]
These should actually be the symbols themselves, *not* the internal constructor names that we use in the abstract syntax (Syntax.hs).

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +[Prefix (reserved "!" >> return (UnaryExpr Negate))]
Please double check the precedence table using the link in the code comment. the order of some of these operators in our `table` does not match the intended order described in the documentation.

When some operators should have the same precedence, then we can simply place them in the same list, as in...
```haskell
    [ Infix (reserved "is" >> return (BinaryExpr Is)) AssocLeft,
      Infix (reservedOp "<" >> return (BinaryExpr Less)) AssocLeft,
      Infix (reservedOp "==" >> return (BinaryExpr Equal)) AssocLeft
    ],
```

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +]
The `break` statement is not an operator, and so it should not be included in this `table`.

Instead, it is a kind of `simpleStmt` and should appear as part of that function.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | BreakStmt
Good, but you can now remove the `NoStmt` placeholder now that you are adding a real kind of statement.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | BreakExpr ForExpr Expression
This is not necessary.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | Break
This is not necessary.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | IsNull
I don't think that there are operators in Adder (i.e., Python) for these, so they should probably not be included here.

2022-11-28 18:39 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | Mod
These are good.

2022-12-01 14:05 UTC, Tientuine requested changes
Just a couple of very small corrections needed and then this will be ready for merge.

2022-12-01 14:05 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
>  [Prefix (reserved "!" >> return (UnaryExpr Negate))]
I'm not sure what this is supposed to be... Python (and thus Adder) does not have the `!` operator.

2022-12-01 16:27 UTC, macc125 commented on src/Adder/Lang/Parser.hs
>  [Prefix (reserved "!" >> return (UnaryExpr Negate))]
- [ x] Negate removed

2022-12-01 16:29 UTC, macc125 commented on src/Adder/Lang/Parser.hs
> +    Prefix (reservedOp "-" >> return (UnaryExpr Negative))
- [ ] Unary Negative moved to proper order of precedence in c9a6928a949f9e78d048b1bdc65a1d7547e457ea

2022-12-01 16:33 UTC, macc125 commented on src/Adder/Lang/Parser.hs
> +    BreakStmt -- finish me!
Solution attempted in c9a6928a949f9e78d048b1bdc65a1d7547e457ea

2022-12-01 16:34 UTC, macc125 commented on src/Adder/Lang/Lexer.hs
> +        ["not", "-",  ">", "<=>", ">=", "and", "is"]
Fixed syntax error with `<=` in c9a6928a949f9e78d048b1bdc65a1d7547e457ea

2022-12-02 04:23 UTC, Tientuine approved these changes
Close enough! The code is okay, but the formatting is still off, including lots of extraneous blank lines added in several places. I'll take care of this during the merge this time, though in the future you can take care to maintain consistent code style.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["not", "-",  ">", "<=", ">=", "and", "is"]
The non-symbolic operators (`not`, `and`, `is`) should be in the reservedNames list instead. Only symbolic operator names should be here. However, in the interest of time, I'll make the change when resolving conflicts during merge.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> + Adding comment to establish my own branch
No need for this comment. I will remove when doing the merge.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    ]
Looks good, though there is no need for the two empty lines.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +  [
Good enough. There will be some editing needed during merge, so I'll fix the formatting at that time.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +
Try to avoid inserting empty lines in the future, as they show up as git changes even though no code has really changed.

2022-12-02 04:23 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +
Again, lots of empty lines here. We'll remove these during merge.

2022-12-02 04:32 UTC, merged