Smith work, Atom creation
Marist-CMPT331-TOPL/adder pull request #26
Opened 2022-11-29 16:06 UTC by Stubeans

Atom syntax code

2022-11-29 16:55 UTC, Tientuine requested changes
We discussed in person in class, so I won't say much more here unless you have new questions that come up.

2022-11-29 16:55 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["yield", "from"],
Fine to have these here, but we will probably not implement these kinds of statements in the interpreter.

2022-12-01 17:49 UTC, Tientuine requested changes
Almost there... I believe you might already have a complete version that's waiting to be pushed, so I will keep an eye out for that.

2022-12-01 17:49 UTC, Tientuine commented on src/Adder/Lang/Lexer.hs
> +        ["yield", "from", "or", "and", "is", "not", "in", "not in", "is not"],
Let's not worry about `yield`, that's one of the language features that we said we would *not* try to implement.

2022-12-01 17:49 UTC, Tientuine commented on app/Main.hs
> + -  Test Line
Get rid of this test line, only useful changes should be included!

2022-12-01 17:49 UTC, Tientuine commented on src/Adder/Defs.hs
> +type Interpreter a = Source -> Either ParseError a
Undo your change to this file - somehow you removed the trailing newline, and there's no need for that change.

2022-12-01 17:49 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +atom = AtomExp <$> Id
This is incorrect, but I believe we already discussed this and you have an un-pushed correction for this on your computer.

2022-12-05 00:16 UTC, Tientuine commented
@Stubeans This piece - identifiers - is one of the crucial pieces remaining in order for us to test parsing a variety of simple programs. Let's get it done! Please let me know if you need help to wrap this one up.

2022-12-05 05:06 UTC, Stubeans commented
@Tientuine I believe I fixed the issues and fixed the Merge Conflicts correctly.

2022-12-05 05:43 UTC, Tientuine approved these changes

2022-12-05 05:43 UTC, merged