Interpret the value of a variable
Marist-CMPT331-TOPL/adder pull request #55
Opened 2022-12-08 12:35 UTC by Tones55

not sure why in interp i have an error, Parse error in pattern: varExp

2022-12-08 13:01 UTC, Tientuine requested changes
A few minor fixes needed, but you're on the right track.

2022-12-08 13:01 UTC, Tientuine commented on src/Adder/Interp.hs
> +valueOf (varExp x) env st0 = Answer (deref addr st0) st0
More more fix needed... To simplify the syntax a bit, in this interpreter implementation I defined an `Answer` to simply be another name for a pair of value and store, rather than its own new data type (see line 70). For this reason, there is no `Answer` constructor, and instead you can create the pair you need just by writing `(deref addr st0), st0)`.

2022-12-15 23:26 UTC, Tones55 commented
I made the changes you suggested

2022-12-16 13:57 UTC, Tientuine approved these changes
The interpreter logic looks correct now. The new function you added to the Parser isn't really needed, but that's fine.

2022-12-16 13:57 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +
It doesn't look like this gets used anywhere, so it's unnecessary, but also doesn't cause any problem, so we'll leave it for now.

2022-12-16 13:58 UTC, merged