StmtList Interp
Marist-CMPT331-TOPL/adder pull request #59
Opened 2022-12-09 16:22 UTC by IanMarsh1

2022-12-10 04:02 UTC, Tientuine approved these changes

2022-12-10 04:07 UTC, Tientuine requested changes
The `_` pattern will match any `Statement`, so when we try to interpret a `StmtList` or `PassStmt`, we'll just get `undefined` instead of running the implementations you wrote. You'll need to move the default case down to below your new cases, so it only handles those statements that don't have a specific implementation.

2022-12-11 16:51 UTC, IanMarsh1 commented
Done. I still want to try and add the helper function; I just won't be able to do it till after the final on Tuesday.

2022-12-12 04:16 UTC, Tientuine approved these changes

2022-12-12 04:16 UTC, merged