English work
Marist-CMPT331-TOPL/adder pull request #68
Opened 2022-12-14 22:04 UTC by MaxEnglish

-Parser is yelling at me a lot and I'm not sure what's the matter with the code I have written there. 
-I remember you said that I'd only need to use resultOfStmts once per function, but I'm not sure how to do that so I just did what I was comfortable with. 
-I realize that you need an else stmt for every if-then-else in Haskell but for ifstmt and ifelif stmt I don't want an else. I believe that's why it's throwing an error for me. How can I circumvent this?

2022-12-16 14:30 UTC, Tientuine requested changes
Inching closer, but one more round of fixes is needed.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Interp.hs
> +resultOf (IfStmt exp1 stmt1) p st = if q then val2
Two issues here:

1. You're trying to use the name `val2` here and on line 70 below, but I don't see any `val2` declared. When the test `q` is true, what you need to return here is the state that results from executing the statements in the list `stmt1`, which down below you've named `s1`. So here, just return `s1` when `q` is true.
2. In Haskell, every if-expression must have an else branch. To implement an `IfStmt` without an `else` part, just make the else do nothing; i.e., when `q` is false, return the same state `st` that you started with.

One final comment on on coding style and consistency - we've generally used a numbering scheme to help understand the order of changes to the program state or free store. So, `st0` would represent the initial state, `st1` the next state, etc. To ensure consistency in the code base, let's try to stick to that naming convention.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Interp.hs
> +resultOf (IfElseStmt exp1 trueStmts falseStmts) p st = if q then val2 else val3
Again, as above, you need to return the new states, `s1` or `s2`, instead of the undeclared `val2` and `val3`.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Interp.hs
> +    (BoolVal q, st) = valueOf exp1 p st
Since evaluating `exp1` might change the free store, you should have a name different from `st` on the left-hand side here. Maybe `st1`?

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Interp.hs
> +    s1 = resultOfStmts stmt1 p val2
Instead of `val2`, which has not been declared, the third argument on the right-hand side should be the state that resulted from evaluating `exp1`, which you should probably name `st1` for consistency. This would make the left-hand side the second new state, so a name like `st2` would be more appropriate.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Interp.hs
> +    s3 = resultOfStmts stmt3 p val5
Apply the same ideas from above to these cases to ensure that you're passing the correct free stores around, and that the naming convention is consistent.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +        <*> (reservedOp ":" >> suite),
All this looks okay.

2022-12-16 14:30 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  | IfElifElseStmt Expression [Statement] [Statement] [Statement]
This all looks fine for now.

2022-12-16 20:24 UTC, MaxEnglish commented
Check "Prescribed Changes" commit for latest work

2022-12-17 01:00 UTC, Tientuine approved these changes
This all looks good, the logic is correct. Some of the variable names you used could be better and there is an extraneous import, but this is good work. Approved!

2022-12-17 01:01 UTC, merged