Smith morework - Atom Implementation Continued
Marist-CMPT331-TOPL/adder pull request #71
Opened 2022-12-16 20:15 UTC by Stubeans

About to push changes...

2022-12-16 20:19 UTC, Stubeans commented
So I moved the valueOfBop above where it's being called, and added a case. However, I realize that the case may be accidentally recursive. Do I have the right idea?

I also consolidated the valueOf statement, and moved the valueOf( BinaryExpr...)... above the undefined case.

2022-12-16 20:38 UTC, Stubeans commented
I fixed a build issue but I'm not sure If i did it correctly. I'm really not sure at all about what valueOfBop does exactly, I assumed I had to call BinaryExpr somehow to reach that code.

2022-12-16 20:40 UTC, Stubeans commented
And I believe I got the try in the right place for the literals fix

2022-12-17 01:14 UTC, Tientuine requested changes

2022-12-17 01:14 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +  AtomExp . try IdAtom <$> identifier
Actually, the `identifier` parser isn't the problem, so you can take that out. It's the parser for float literals that's the problem, that's where you need to add the `try`. However, the `try` function takes a parser, so you'll need to wrap the float literal parser in parentheses to to make sure Haskell does the order of operations correctly... e.g., `try (FloatLiteralExp <$> float)`.

2022-12-17 01:14 UTC, Tientuine commented on src/Adder/Interp.hs
> +
Although it won't cause a problem here, I specifically had a comment below for where we should put auxiliary/helper functions. So, let's keep them down there. Please put this back down below and put the `{- Auxiliary functions -}` comment back in also. Thanks!

2022-12-17 01:14 UTC, Tientuine commented on src/Adder/Interp.hs
> +  _ -> (val1, emptyStore)
There's no need for this case... your error case is enough here.

2022-12-17 01:14 UTC, Tientuine commented on src/Adder/Interp.hs
> +valueOf (BinaryExpr op exp1 exp2) env st0 = valueOfBop op val1 val2
You still need to return the free store on the right-hand side along with the result of `valueOfBop`. That's still missing. Just take your whole `valueOfBop` function call with all its arguments and make that the first element of a pair, where the second element of the pair is the most recent free store, which in your case is `st2` since that's the one you ended up with after evaluating `exp2`.

2022-12-17 02:35 UTC, Stubeans commented on src/Adder/Interp.hs
> +valueOf (BinaryExpr op exp1 exp2) env st0 = valueOfBop op val1 val2
I'm about to push the change, however I don't quite understand why it's on this line. I thought that the right side of the = was a way of saying to pass the values on the left side into the values on the right, not that we're saying that the answer to the BinaryExpr is the right side. Did I explain that right? So we're basically saying that, given these expressions, where < the logic >, the answer is = to this?

Also, as a side note. When I changed the right side to an answer pair, I had to change the valueOfBop to return an ExpVal since that's what the answer was expecting. I hope that's correct.

2022-12-17 03:17 UTC, Tientuine commented on src/Adder/Interp.hs
> +valueOf (BinaryExpr op exp1 exp2) env st0 = valueOfBop op val1 val2
If I'm understanding you correctly, then I think I understand where the confusion is.

When we define a function in Haskell, just like any other language the right-hand side describes the result.
```haskell
-- This function says that if we call `f` on some Double value that we'll name `x`,
-- then it will return another Double value that is equivalent to that `x` squared plus 1.
f :: Double -> Double
f x = x**2 + 1
```

I think maybe the confusion arises when we use the `where` clause to define other names. For example,
```haskell
-- This function says that if we call `g` on some Double value that we'll name `x`,
-- then it will return another Double value that is equivalent to that `x` squared plus 1.
-- But this function does so by naming the `x` squared part as `w` first, and then returning `w` plus 1.
g :: Double -> Double
g x = w + 1
  where
    w = x**2
```

In any case, the type name that appears last (i.e., farthest to the right) in our function type is the return type. So whatever is on the right-hand side of a function definition has to match that type.

```haskell
-- This type of this function says that it returns a pair of integer and double, so
-- the right-hand side must be a pair of integer and double. In this particular
-- case, the function `h` takes `x` and `y` and returns a pair containing `x` plus 1
-- as the first element of the pair and `y` divided by 2 as the second.
h :: Integer -> Double -> (Integer, Double)
h x y = (x + 1, y / 2)
```

2022-12-17 03:21 UTC, Tientuine requested changes

2022-12-17 03:21 UTC, Tientuine commented on src/Adder/Interp.hs
> +  --Code here
I would still like to see this function definition placed down below under the `{- Auxiliary functions -}` comment like you had it originally.

2022-12-17 03:21 UTC, Tientuine commented on src/Adder/Interp.hs
> +valueOf (BinaryExpr op exp1 exp2) env st0 = (valueOfBop op val1 val2, st2)
This is correct now, because `valueOfBop` returns an `ExpVal` and `st2` is a free `Store`, so the right-hand side now produces a pair of those two things.

2022-12-17 03:21 UTC, Tientuine commented on src/Adder/Lang/Parser.hs
> +    <|> FloatLiteralExp <$> float
Just need to fix this part by removing the `try` from the `IdAtom` rule and instead moving it to the float literal rule.

2022-12-17 03:21 UTC, Tientuine commented on src/Adder/Lang/Syntax.hs
> +  show (FloatVal p) = show p
This didn't need to be moved, but that's okay, we can leave it here.

2022-12-17 03:27 UTC, Stubeans commented
Should be all good now. I was able to build and run.

2022-12-17 04:36 UTC, Tientuine approved these changes

2022-12-17 04:39 UTC, merged